# compose.yml
services:
    yt:
        build:
            context: .
            dockerfile: Dockerfile
        image: llama3-8bft:latest
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        environment:
            - DISPLAY=:0
            - NVIDIA_DRIVER_CAPABILITIES=all
            - NVIDIA_VISIBLE_DEVICES=all
            - DEBUG_COLORS=1
            - TERM=xterm-256color
            - COLORTERM=truecolor
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - .:/app:rw
            # cache
            - ./data/huggingface_cache:/root/.cache/huggingface
            - ./data/pip_cache:/root/.cache/pip
        tty: true
        ipc: host
        ulimits:
            memlock: -1
            stack: 67108864
        shm_size: '8gb'
        stdin_open: true

        runtime: nvidia